const express=require('express')
const usersignup = require('../Controller/usersignup')
const check = require('../Controller/userlogin')
const protect = require('../middleware/token')
const addStore = require('../Controller/Store/addStore')
const addProducts = require('../Controller/Product/addProduct')
const getitemsname = require('../Controller/Product/searchproducts')
const getdata = require('../Controller/Store/SearchStoreById')
const userList = require('../Controller/userFindAll')
const deleteuser = require('../Controller/userdelete')
const storeList = require('../Controller/Store/findAllStore')
const deleteStore = require('../Controller/Store/deleteStore')
const checkstore = require('../Controller/Store/storeLogin')
const showstore = require('../Controller/Store/findStoreById')
const middleware=[protect]
const  router=express.Router()

router.route('/signup').post(usersignup)
router.route('/login').post(check)
router.route('/loginstore').post(checkstore)
router.route('/addstore').post(addStore)
router.route('/addproducts').post(addProducts)
router.route('/products/:Name').get(getitemsname)
router.route('/store/:id').get(getdata)
router.route('/findallusers').get(userList)
router.route('/delete/:id').delete(deleteuser)
router.route("/findallstores").get(storeList)
router.route('/deletestore/:id').delete(deleteStore)
router.route("/findstorebyid/:id").get(showstore)

module.exports=router